#!/bin/sh -eu

VERSION_FILE="src/VERSION"

check_git_has_no_unstaged_changes() {
  if ! git diff-files --quiet ; then
     echo "git repo has unstaged changes"
     exit 1
  fi
}

check_local_master_equals_remote_master() {
  BRANCH_A="master"
  BRANCH_B="origin/master"

  if [ x"$(git rev-parse $BRANCH_A)" != x"$(git rev-parse $BRANCH_B)" ]
  then
        echo "ERROR: $BRANCH_A is not equal to $BRANCH_B"
        exit 2
  fi
}

checkout_master() {
  git fetch
  git checkout master
}

print_current_version() {
  CURRENT_VERSION=$(cat ${VERSION_FILE})
  echo "Current version is ${CURRENT_VERSION}"

}

prompt_for_new_version() {
  read -p "Enter new version: " NEW_VERSION
  echo "New version is ${NEW_VERSION}"
}

modify_source_files() {
  sed -i "s/^\/\/ version: .*/\/\/ version: ${NEW_VERSION}/g" src/fluidkeys.go
  sed -i "s/^Version: .*/Version: ${NEW_VERSION}/g" pkg/debian/DEBIAN/control
  echo -n "${NEW_VERSION}" > "${VERSION_FILE}"
}


git_add_modified_source_files() {
  git add src/fluidkeys.go pkg/debian/DEBIAN/control "${VERSION_FILE}"
}

make_upversion_commit() {
    set -x  # enable command echo
    git commit --gpg-sign -m "Release ${NEW_VERSION}"
    set +x  # disable command echo
}

make_signed_tag() {
    set -x  # enable command echo
    git tag --sign "v${NEW_VERSION}" -m "v${NEW_VERSION}"
    git tag -f --sign release -m release
    git tag --list
    set +x  # disable command echo
}

instruct_git_push() {
    echo
    echo "In a new shell, verify with:"
    echo "  git log --show-signature"
    echo "  git tag --verify ${NEW_VERSION}"
    echo
    echo "Then press RETURN to push to origin, eg:"
    echo "  git push origin master:master"
    echo "  git push origin --tags"
    echo
    echo "(or press ctrl-c to quit now)"

    read DUMMY
}

push_to_origin() {
    set -x  # enable command echo
    git push origin master:master
    git push origin --tags
    set +x  # disable command echo
}

check_git_has_no_unstaged_changes
checkout_master
check_local_master_equals_remote_master
print_current_version
prompt_for_new_version
modify_source_files
git_add_modified_source_files
make_upversion_commit
make_signed_tag
instruct_git_push
push_to_origin
