#!/bin/sh -eu

# Note: don't try and compile outside of $GOPATH. It only lead to misery.
# This used to test that `make compile` could be run from anywhere, but it's
# not worth the hassle.

THIS_FILE=$0
THIS_DIR=$(dirname $0)

test_make_compile_runs() {
    make compile || exit 1
}

ensure_fk_binary_exists_in_build() {
  if [ ! -f "${THIS_DIR}/../build/bin/fk" ] ; then
      echo "Binary doesn't seem to have been installed in build/bin/fk"
  fi
}

print_success() {
    echo 'OK: `make compile` ran successfully'
}

test_make_compile_runs
ensure_fk_binary_exists_in_build
print_success
